### ISSUE TITLE
[Bug] Toggle messed up in Firefox

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1044]
The toggle component is not rendering properly in Firefox.

![screen shot 2018-11-29 at 10 24 28 am](https://user-images.githubusercontent.com/424119/49236193-3815f180-f3c1-11e8-8af7-305692bdbebb.png)

**Comment by ckoutsiaris** [comment]
@xak @saadmhybris @eboyer @ianquigley-sap @ritarora 

In order to fix this issue, I had to use a different approach for the toggle component. The biggest change is that now instead of a span it is a label.  Can you please check this [test PR](https://github.com/SAP/fundamental/pull/1066/files#diff-880c4f8686a82f8feb88f97202060339) and let me know what you think? If it is ok with you then I will create a new PR which replaces the current toggle with the one from the test PR.

You can see a demo of it here:
https://deploy-preview-1066--fundamental.netlify.com/components/togglev2.html

![screenshot 2018-12-05 at 14 39 57](https://user-images.githubusercontent.com/44162302/49520673-abc16e00-f89b-11e8-9f99-8c215ec9ca7b.png)

**Comment by xak** [comment]
We can't have two labels since that is malformed HTML and will cause some a11y issues. However. when I edit the HTML and change the `label` to a span your solution works fine. There should be almost no difference between the two, the browser defaults for  both are nothing. The `label` shouldn't give you anything here that the `span` can't.

![screen shot 2018-12-05 at 6 00 46 pm](https://user-images.githubusercontent.com/424119/49552112-c0136400-f8b7-11e8-803c-1a40cfcd1bab.png)

It's worth noting that the ids are duplicated in the `docs` page which is preventing proper testing. Each label and input should have unique ids including the panel background switcher toggle.

**Comment by ckoutsiaris** [comment]
Thanks, @xak , here is the PR https://github.com/SAP/fundamental/pull/1081
