### ISSUE TITLE
JS: Improve demonstration JS to simulate states

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1090]
The test framework and website should simulate behaviors as best we possibly can. Specialized JS is in place for dropdowns and some inputs, for example, but it can be improved to better simulate the desired behaviors. 

> NOTE: This is not about creating JS that will be distributed with the library, but only to simulate the behavior

- [ ] All popovers should close when clicking off the popover or when opening another popover.
- [ ] The `search-input` collapsed variant should open when clicking the icon, once open the icon submits the search, the only way to close it once open is `val.length=0` and clicking off the component.

**Comment by kannankumar** [comment]
Hi, 
What is the current way to get the Popovers to close when clicking off the popover ?
I couldn't find any recommended way in the docs.

**Comment by saad-mo** [comment]
@kannankumar - 

Since fundamentals is a CSS library we do not deliver any javascript. Any javascript behavior you see on the documentation site is for demo purpose only.  

You can easily hide the popover by setting `aria-expanded` to `false` on the popover control (`fd-popover__control`) and `aria-hidden` to `true` on the popover body (`fd-popover__body`). 

Hope this helps

**Comment by kannankumar** [comment]
It definitely helps to know which classes and `aria` attributes to use.

Thanks a lot @saad-mo for your quick response.
