### ISSUE TITLE
Lib: Inline help should work with any content

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1132]
There are many times when I may want to use the `inline-help` component without the default `?` icon. For example, text in a paragraph like a definition or providing more context to a label.

> Should this be a `tooltip`?

I would like to have the entire label be the trigger for the help text without the icon. The text should also be enforced as normal case and weight.

<img width="593" alt="screen shot 2018-12-19 at 9 22 35 am" src="https://user-images.githubusercontent.com/424119/50229333-b6860380-036f-11e9-9c80-b8a669bbf328.png">

**Comment by saad-mo** [comment]
The `inline-help` is too specific for its use cases and would require major refactoring to accomplish this and potentially causing breaking changes. The recommendation is to create a new `tooltip` component that can be applied to anything element.

**Comment by bcullman** [comment]
looks like inline help is just a composition of an icon and a popover (or a tooltip, which really is a special kind of popover). And because it include the icon, the consumer doesn't need to be information about what element it is attached to - it is *always* attached to the "?".

If the consumer does not want the icon, why not just have them not use this composition, and just the base popover (or tooltip)? They are going to have to attach it to *something* on the page anyway, and that is the use case popover and tooltip already support.
