### ISSUE TITLE
Fiori 3 ?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#1512]
I have two questions about Fiori 3 and Fundamentals / Fiori 3 relation:

1. To my understanding, SAP Fundamentals and UI5 both implement new SAP design standard Fiori 3. Is that correct and still correct after #1510 and #1511 ?

2. Where I could find more info on Fiori 3 standard? On portals like below, no info at all, not even a Fiori 3 "in progress":
  * https://design.sap.com/fiori-ux.html
  * https://experience.sap.com/fiori-design-web/sap-fiori/
Is any public info on Fiori 3 available and why not hyperlink from your README ?

**Comment by saad-mo** [comment]
Hi @bsrdjan, 

#1 Yes, this is still correct. We are removing Fiori 3 references because Fiori is a design language and Fundamentals is an Open source project that implements these Guidelines and independent of the Fiori Team and brand. 

#2 Fiori 3 are guidelines are still work in progress and not available outside the organization. If you need internal links for reference, please email me and I can provide those to you.
