### ISSUE TITLE
Error message installing SAP font

### ISSUE THREAD

**Issue by ckrenn** [SAP/fundamental#1542]
I need to install the SAP 72 font.  I've downloaded it, but when we try to install it, it says it is not a valid font file.  Please send me the correct file.

![GifHub Font Error](https://user-images.githubusercontent.com/64862828/81100495-43cce800-8ed2-11ea-8bca-34b2ddfd9ee2.jpg)

**Comment by sebastian-friedrich** [comment]
Did you tried to extract the zip file into a folder on your hard disk first instead of directly accessing files from within the archive? Windows Explorer is able to reveal and interact with content within zip archives directly just like it would be regular folder, but this is kind of virtual on top of the actual NTFS filesystem what is maybe why this might come into your way here.
