### ISSUE TITLE
Visuals: Combobox

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#348]
An enhanced dropdown with a search option.

https://openui5.hana.ondemand.com/#/entity/sap.m.ComboBox
https://select2.org/selections

**Comment by xak** [comment]
#349

**Comment by LeoT7508** [comment]
@xak @jeannewalters 

Combobox:
https://zpl.io/VOWJwxj

**Comment by LeoT7508** [comment]
@xak 

What else do you need to see here?

**Comment by xak** [comment]
@Jagoooo I'm open to suggestions on what we call this. `Combobox` is not the best option when it's more of a searchable/filterable dropdown.

**Comment by xak** [comment]
@LeoT7508 See my comments in Zeplin.

**Comment by Jagoooo** [comment]
My thoughts are.

Combo Box 
Agree  

Combo box (Two columns layout) 

 Combo box with icon (Because this could be a Image or value)

  Combo box - Lazy loading 
Autocomplete Combo box

  Combo box (Search in both columns)

 Searchable Combo box 
I did not see if you had a single search, if so call one “single search combo box” and the other “dual search combo box”

**Comment by LeoT7508** [comment]
@xak @saadmhybris @Jagoooo 

Updated design sheet here:

https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b2ab49a7406ff8d18c6df41

**Comment by Jagoooo** [comment]
We are closing this as we have created a new ticket with further info

**Comment by saadmhybris** [comment]
@Jagoooo pls add the link to the new issue here

**Comment by Jagoooo** [comment]
Here are my wires for the Combo box with a number of different scenarios
Tagging, Single select, multiple select and select or create.

https://uu7pjq.axshare.com/#g=1&p=dashboard

**Comment by Jagoooo** [comment]
I have created a new issue. The link is below.

https://github.com/SAP/fundamental/issues/520
