### ISSUE TITLE
Lib: Implement calendar component

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#353]
### Blocks #417 

https://openui5.hana.ondemand.com/#/entity/sap.ui.unified.Calendar

Implement a `calendar` component that can be used by the date-picker.

We cannot provide a functioning calendar. Our priority should be to demonstrate the states of the calendar — current, selected, range selected, etc. — as well as spacing. 

### Examples
https://codepen.io/joe-watkins/pen/KsAgp

**Comment by LeoT7508** [comment]
@xak 

Date & Time picker design sheet:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5aff064bfdf1003421ee2d28

**Comment by xak** [comment]
@LeoT7508 and @jeannewalters The basic calendar is completed. The test page is available at http://localhost:3030/calendar in branch `develop`. 

See reminder how to run local testing pages — https://github.com/SAP/fundamental/blob/develop/test/README.md#how-to-test-a-feature-branch

**PDF of that page**
[calendar.pdf](https://github.com/SAP/fundamental/files/2055908/calendar.pdf)

**Screen recording of month/year switching**
https://sap.sharepoint.com/:v:/s/85000013/EY-msF5kVjNJt-F9ZS4eIRkBtcPRE4oXoXpdkD1kiI3YXw?e=ltmpR3

**Comment by saadmhybris** [comment]
@LeoT7508 @jeannewalters - have you guys had a chance to look at this yet?

**Comment by LeoT7508** [comment]
@saadmhybris 

Two small issues I see here:

.fd-calendar__item--blocked
&
.is-blocked

These should be normal read only colored text since they aren't clickable. You can see the example here: 
https://zpl.io/29DGRkW
Listed under "Non selectable dates"

Also a miss from my side, we should add a shadow behind the container to create that separation when displayed on a white. You can find the details in that same design sheet listed above.

**Comment by xak** [comment]
## Address bugs above
