### ISSUE TITLE
Bug: FUI Table lacks in colors

### ISSUE THREAD

**Issue by ivijan** [SAP/fundamental#628]
## Issue
* fundamental-UI table lacking background color specification for whole table background
* fundamental-UI table lacking active row background color specification

There is a blue color defined for row with checked checkbox, should this color be used also for active row?
If we add white background color to whole table background, then the row hover color is not visible.

## Demo page screens:
![screen shot 2018-08-22 at 09 37 43](https://user-images.githubusercontent.com/13087038/44449799-6ed4b280-a5ef-11e8-8ce6-f19013ddaccb.png)
![screen shot 2018-08-22 at 09 19 05](https://user-images.githubusercontent.com/13087038/44449810-7300d000-a5ef-11e8-8d6b-661b437ede87.png)
![screen shot 2018-08-22 at 09 41 52](https://user-images.githubusercontent.com/13087038/44449878-a6dbf580-a5ef-11e8-9670-d60820351b1b.png)

## Additional information
> Browser and environment: Chrome v67.x on Mac High Sierra v10.x
> Version of the Fundamental UI: **v1.1.0**
> Front-end framework: **Angular 6**

**Comment by sbgreene1307** [comment]
We also have some issues with the table's coloring. 
The table rows get background color of #fff (white) when the table row is hovered over. Since most of the layout elements (panel, tile, etc) have a default of white as well, you cannot see the hover css being applied. Since I want the panel background to be white, I had to write custom css to use a different color for the table row background on hover.

**Comment by ckoutsiaris** [comment]
We added some default styling to the tables. It should be ok now. Thanks
