### ISSUE TITLE
Design - Responsive popover

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#655]
Pop over - document when to scroll and max height
Investigate whether these should be used for dropdowns too?
What is the max height for mobile, tablet, desktop - should they be different? Add a scroll bar once the user hits the max height. 
What is the width and what happens if the text is too wide?

**Comment by Jagoooo** [comment]
I have spoken to our lead front-end developer Artsiom about using pop overs for drop-downs. We did a bit of research and most of the modern applications are going that way.  So we agreed we should role with the times! 

Width should truncate to accommodate for text. 
Mobile - Max width 300px Leaving 10px each side

Tablet and desktop fixing to 400px because they look silly if they span across the screen.

**Comment by Jagoooo** [comment]
![screen shot 2018-09-19 at 17 26 22](https://user-images.githubusercontent.com/38916020/45767744-f0d9ea80-bc32-11e8-892e-e29da63cba51.png)

**Comment by Jagoooo** [comment]
![popovers](https://user-images.githubusercontent.com/38916020/45805732-43f58100-bcb7-11e8-97b8-1a08a85b1db1.png)

**Comment by jeannewalters** [comment]
Closed - Duplicate of #938
