### ISSUE TITLE
Bug: GRID - Remove columns from spec table

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#904]
## Detailed description

The spec table on the grid page is incorrect. The columns have not yet been implemented and should not be in the table.

Also, the Margin (A) and Gutter (B) headers do not make sense with no reference image.

- remove columns column
- remove (A) and (B)

Design story - #801

**Comment by saadmhybris** [comment]
need some more information on what needs to be updated. 

@LeoT7508 do you have correct specs for the table and visuals that need to go on this page? 

This the page in question - https://sap.github.io/fundamental/foundation/grid.html

**Comment by LeoT7508** [comment]
@saadmhybris 

Do you have a link to what you are referring to?

**Comment by saadmhybris** [comment]
@LeoT7508 

This is what we used to have before on the grid page - https://zpl.io/awykjx1

Since the update to the design system, all these visuals are outdated and hence removed which leaves us with this page - https://sap.github.io/fundamental/foundation/grid.html

I don't think we necessarily need to redo this page the same way the old one was, but need to explain how the grid works we can discuss this further.
