### ISSUE TITLE
Fixed Table Column Width

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#914]
The documentation contains [an example of a table with a fixed table column](https://sap.github.io/fundamental/components/table.html#table-with-fix-column-header-and-context-menu). When I tried to change the width of the fixed table column (300px instead of 200px) I see strange artefacts.

<img width="832" alt="table" src="https://user-images.githubusercontent.com/153225/48128693-79662600-e287-11e8-92f8-c2915c51c25e.png">

I have deployed [a minimal example](https://bugs-ytwbprregp.now.sh/) which shows the problem (at least in the latest stable Chrome on the latest stable version of macOS).

I also noticed that the documentation linked above contains malformed html:

![mal](https://user-images.githubusercontent.com/153225/48128781-d06bfb00-e287-11e8-8f65-7c33c614c0fa.png)

I also tried to fix those issues locally but the problem described above persists.
It is of course also possible that I am doing something wrong w/r to changing the width of the table column.

**Comment by saadmhybris** [comment]
@ChristianKienle 

- if you need to extend the width of the fixed column, you also need to adjust the `left-padding` on `fd-table--fixed` class by the same amount. Ideally, this value should be set by javascript on elements, but since we do not provide JS with Fiori Fundamentals, you would have to do this in your project during implementation. 
- the space you see between the table cells on the fixed column id due to text wrapping on the non-fixed column. We'll try to fix this issue. 
- we will fix the inline styles on the table cells with -  #943
